name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?
      placeholder: I tried... but...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of telclaude does this affect?
      options:
        - Security (observer, approvals, rate limiting)
        - Permissions (tiers, identity linking)
        - Telegram (bot, messaging)
        - SDK (Claude integration, session pool)
        - Sandbox (OS isolation)
        - TOTP (2FA daemon)
        - CLI (commands, output)
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this?
      options:
        - label: I would be willing to submit a PR for this feature
