import { DEFAULT_ALLOWED_DOMAIN_NAMES } from "./domains.js";

const FIREWALL_ONLY_DOMAINS = [
	"api.telegram.org",
	"telegram.org",
	"api.x.com",
	"x.com",
	"twitter.com",
	"abs.twimg.com",
	"pbs.twimg.com",
	"t.co",
	"hub.docker.com",
	"registry-1.docker.io",
	"auth.docker.io",
] as const;

export const FIREWALL_WILDCARD_EXPANSIONS: Record<string, readonly string[]> = {
	"*.stackexchange.com": [
		"superuser.com",
		"serverfault.com",
		"askubuntu.com",
		"unix.stackexchange.com",
		"security.stackexchange.com",
	],
	"*.claude.ai": ["www.claude.ai", "console.claude.ai"],
	"*.code.anthropic.com": ["www.code.anthropic.com", "console.code.anthropic.com"],
};

function dedupePreserveOrder(domains: readonly string[]): string[] {
	const seen = new Set<string>();
	const ordered: string[] = [];
	for (const domain of domains) {
		const normalized = domain.trim().toLowerCase();
		if (!normalized || seen.has(normalized)) continue;
		seen.add(normalized);
		ordered.push(normalized);
	}
	return ordered;
}

export function getFirewallAllowedDomains(): string[] {
	const sandboxDomains = DEFAULT_ALLOWED_DOMAIN_NAMES.flatMap((domain) => {
		if (!domain.startsWith("*.")) {
			return [domain];
		}
		return [...(FIREWALL_WILDCARD_EXPANSIONS[domain] ?? [])];
	});

	return dedupePreserveOrder([...sandboxDomains, ...FIREWALL_ONLY_DOMAINS]);
}

export function renderFirewallAllowedDomainsShellScript(): string {
	const lines = [
		"# Generated by scripts/generate-firewall-domains.ts. Do not edit by hand.",
		"ALLOWED_DOMAINS=(",
		...getFirewallAllowedDomains().map((domain) => `    "${domain}"`),
		")",
		"",
	];
	return lines.join("\n");
}
